export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_SUCCESS = " MOVIES_SUCCESS";
export const MOVIES_FAIL = "MOVIES_FAIL";

export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_SUCCESS = " MOVIE_SUCCESS";
export const MOVIE_FAIL = "MOVIE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

